language: "java"

before_install:
  - "./gradlew clean"
  - "./docker-login.sh"

install:
  - "./gradlew build"
  - "docker build . -t filipmalczak/fusionauth-x:1.6.1"

script:
  - "docker push filipmalczak/fusionauth-x:1.6.1"

after_script: "docker logout"