language: "java"

before_install:
  - ./gradlew clean
  - source ./scripts/docker-login.sh

install:
  - ./gradlew build
  - source ./scripts/docker-build.sh

script:
  - source ./scripts/docker-push.sh

after_script:
  - docker logout